### ISSUE TITLE
DOT address is showing KSM transactions

### ISSUE THREAD

**Issue by dcolley** [nova-wallet/nova-ios-app#2]
I added our DOT Pool #18 Stash Address: 13UVJyLnbVp8c4FQeiGDrYotodEcyAzE8tipNEMc61UBJAH4

The DOT figure is correct. Why is it showing KSM...?

![IMG_7618](https://user-images.githubusercontent.com/1845970/210653526-598642dd-09f0-47e4-ad91-7398be8a5507.png)

**Comment by dcolley** [comment]
It seems you are showing KSM from Pool #18 which is for PolkaGate | https://polkagate.xyz

**Comment by ERussel** [comment]
Hey hey! Looks like the same account id is used also for KSM pool. So it is expected behaviour that you see balances in both networks

**Comment by dcolley** [comment]
Ok, but that account on Kusama is not mine…
