### ISSUE TITLE
Participation in Acala's liquid crowdloan is visible as locked DOT

### ISSUE THREAD

**Issue by darko-mijic** [nova-wallet/nova-ios-app#3]
The Nova wallet shows a locked DOT balance for participation in Acala's liquid crowdloan, even though the Acala protocol (Acala's Liquid Crowdloan vault) owns those DOT tokens, not my wallet.

Not sure if the same issue exists for other liquid crowdloans.

I hope you find this issue worth fixing.

**Comment by ERussel** [comment]
Hey hey! Nova wallet displays all balance that is spent for crowdloans as locked balance. So it is expected behaviour.
